##################################################################################################
# Config for normal work loads
##################################################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: nginx-system
  labels:
    app: nginx-server
spec:
  replicas: 40
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      topologySpreadConstraints:
      - maxSkew: 4
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: nginx-server
      containers:
      - name: nginx-server
        image: gcr.io/tigera-dev/suresh/http-nginx:timeout
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: nginx-system
  labels:
    app: nginx-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx-server

